[package]
name = "clippy-no-deps"
version = "0.1.0"
edition = "2021"

[dependencies]
a-dep = { workspace = true }

[workspace]
members = ["a-dep", "b-dep"]

[workspace.dependencies]
a-dep = { path = "a-dep" }
b-dep = { path = "b-dep" }
